{
 "title": "batch_dashboard",
 "tags": [
  "BDA",
  "batch",
  "Sanidad"
 ],
 "time": { "from": "2025-05-08T00:00:00.000Z", "to": "2025-05-18T00:00:00.000Z" },
 "panels": [
  {
   "title": "Recuento de Bacterias en Analíticas",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "MedicineDB",
     "rawSql": "SELECT \r\n  bacteria_detected,\r\n  COUNT(analitica_id) AS total_analiticas\r\nFROM MedicineDB.analiticas\r\nGROUP BY bacteria_detected;\r\n"
    }
   ]
  },
  {
   "title": "Recuento de Bacterias por tipo de muestra",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "MedicineDB",
     "rawSql": "SELECT \r\n  bacteria_detected,\r\n  sample_type,\r\n  COUNT(analitica_id) AS total_analiticas\r\nFROM MedicineDB.analiticas\r\nGROUP BY bacteria_detected, sample_type;\r\n\r\n"
    }
   ]
  },
  {
   "title": "Histórico de Bacterías",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "dataset": "MedicineDB",
     "rawSql": "SELECT \r\n  sample_date AS time,\r\n  CONCAT('Bacteria: ', bacteria_detected) AS metric,\r\n  COUNT(analitica_id) AS value\r\nFROM MedicineDB.analiticas\r\nGROUP BY sample_date, bacteria_detected\r\nORDER BY sample_date;\r\n"
    }
   ]
  },
  {
   "title": "Recuento de tipos de muestras",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "dataset": "MedicineDB",
     "rawSql": "SELECT \r\n  sample_type,\r\n  COUNT(analitica_id) AS total_analiticas\r\nFROM MedicineDB.analiticas\r\nGROUP BY sample_type;"
    }
   ]
  }
 ]
}